import { Listing, Booking, Transaction, ChatMessage } from "./types";

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: "bourdillon-penthouse",
    title: "The Bourdillon Penthouse",
    description: "A breathtaking, futuristic duplex penthouse in the absolute heart of Ikoyi, Lagos. Features extensive double-height glass facades that offer pure 180-degree panoramic sweeps of the Victoria Island skyline and the glittering lagoon below at sunset. Outfitted with tailor-made leather sofas, a private wellness gym setup, custom brass and marble fixtures, and full motorized curtain integration for absolute light-level control.",
    category: "Penthouse",
    location: "Ikoyi",
    bedrooms: 4,
    bathrooms: 4.5,
    maxGuests: 8,
    squareFootage: 5500,
    nightlyRate: 450000,
    weekendPremium: 15,
    cleaningFee: 25000,
    securityDeposit: 150000,
    image: "assets/images/horizontal/IMG-20260621-WA0002.jpg",
    images: [
      "assets/images/horizontal/IMG-20260621-WA0002.jpg",
      "assets/images/horizontal/IMG-20260621-WA0003.jpg"
    ],
    amenities: ["24/7 Power", "Infinity Pool", "Private Chef", "Concierge", "High-Speed Wi-Fi", "Private Gym"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 32,
    rating: 4.9,
    aiMatchPercent: 98,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "lagoon-view-villa",
    title: "Lagoon View Villa",
    description: "Set directly on the private shoreline of Banana Island, this striking architectural achievement merges concrete facades with a tropical courtyard. Complete with an infinity lap pool that spills into the serene lagoon waters, a carded wool textile audio-shield acoustic system in the lounge room, a separate wine cellar, gourmet outdoor al fresco dining pavilion, and direct private deep-water dock access supporting yacht drop-offs.",
    category: "Luxury Villa",
    location: "Banana Island",
    bedrooms: 5,
    bathrooms: 6.0,
    maxGuests: 10,
    squareFootage: 8000,
    nightlyRate: 650000,
    weekendPremium: 15,
    cleaningFee: 35000,
    securityDeposit: 250000,
    image: "assets/images/horizontal/IMG-20260621-WA0004.jpg",
    images: [
      "assets/images/horizontal/IMG-20260621-WA0004.jpg",
      "assets/images/horizontal/IMG-20260621-WA0005.jpg"
    ],
    amenities: ["24/7 Power", "Infinity Pool", "Private Chef", "Concierge", "High-Speed Wi-Fi", "Yacht Access", "Wine Cellar"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 18,
    rating: 4.8,
    aiMatchPercent: 94,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "eko-loft",
    title: "The Eko Loft Sanctuary",
    description: "An exceptional, industrially inspired loft featuring towering double-height concrete ceilings and immense black frame ironmongery windows. Placed securely within upscale Victoria Island. Styled in close co-creation with local master carvers and modern African abstract painters. Offers a highly peaceful, safety-engineered sound insulation setup making the buzz of the metropolis vanish entirely.",
    category: "Executive Studio",
    location: "Victoria Island",
    bedrooms: 2,
    bathrooms: 2.0,
    maxGuests: 4,
    squareFootage: 2500,
    nightlyRate: 250000,
    weekendPremium: 10,
    cleaningFee: 15000,
    securityDeposit: 80000,
    image: "assets/images/horizontal/IMG-20260621-WA0122.jpg",
    images: [
      "assets/images/horizontal/IMG-20260621-WA0122.jpg",
      "assets/images/horizontal/IMG-20260621-WA0124.jpg"
    ],
    amenities: ["24/7 Power", "High-Speed Wi-Fi", "Concierge", "Safety-pact Lock system", "Acoustic Shielding"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 45,
    rating: 4.7,
    aiMatchPercent: 91,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "ekpo-apartment",
    title: "Ekpo - Luxury 1-Bedroom",
    description: "Our Unique Studio Bedroom Apartment with Swimming Pool, Smartlock Door, complimentary breakfast, and Gym 😍✨",
    category: "Serviced Apartment",
    location: "Lekki Phase 1",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    squareFootage: 1200,
    nightlyRate: 180000,
    weekendPremium: 15,
    cleaningFee: 15000,
    securityDeposit: 50000,
    image: "assets/images/horizontal/IMG-20260621-WA0002.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0002.jpg"],
    amenities: ["24/7 Power Supply", "Treated Water Supply", "High-Profile Security", "Unlimited Internet", "DSTV & Netflix", "Housekeeping Service", "Swimming Pool", "Fully Equipped Gym"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 12,
    rating: 4.8,
    aiMatchPercent: 95,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "whitestone-2br",
    title: "Whitestone - Luxury 2BR",
    description: "Luxury 2bedroom Apartment with swimming pool",
    category: "Luxury Villa",
    location: "Lekki Phase 1",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    squareFootage: 1800,
    nightlyRate: 270000,
    weekendPremium: 15,
    cleaningFee: 20000,
    securityDeposit: 100000,
    image: "assets/images/horizontal/IMG-20260621-WA0003.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0003.jpg"],
    amenities: ["Swimming Pool", "Luxury Living"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 8,
    rating: 4.7,
    aiMatchPercent: 90,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "maisonette-lekki",
    title: "Lekki Maisonette",
    description: "Newly opened 2bedroom Maisonette apartment Located at off freedom way babalola garden street",
    category: "Serviced Apartment",
    location: "Lekki Phase 1",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    squareFootage: 2200,
    nightlyRate: 210000,
    weekendPremium: 10,
    cleaningFee: 25000,
    securityDeposit: 120000,
    image: "assets/images/horizontal/IMG-20260621-WA0004.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0004.jpg"],
    amenities: ["Gated and Secured Estate", "24-hour Electricity", "24-hour Safety & Security", "Guest Parking Space", "Smart TV & Netflix", "Superfast Internet", "standard gym house", "Standard Swimming Pool", "standard outdoor table tennis", "Chef on request", "Spacious Living Areas & Private Balcony", "High-Quality Bedding and Linens", "Washing Machine", "Bespome Interior Decoration", "Netflix", "Ps5", "Cleaning services"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 5,
    rating: 4.9,
    aiMatchPercent: 97,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "victoria-penthouse",
    title: "Victoria Penthouse",
    description: "Luxury 3 bedroom penthouse with cinema",
    category: "Penthouse",
    location: "Victoria Island",
    bedrooms: 3,
    bathrooms: 3.5,
    maxGuests: 6,
    squareFootage: 3500,
    nightlyRate: 380000,
    weekendPremium: 20,
    cleaningFee: 30000,
    securityDeposit: 200000,
    image: "assets/images/horizontal/IMG-20260621-WA0111.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0111.jpg"],
    amenities: ["Gated and Secured Estate", "24/7 Power Supply", "Serene environment", "Smart Lock", "Very fast internet", "Netflix / YouTube / Dstv", "Snooker Board", "Swimming pool", "Gym", "En-suite room with Balcony", "Cinema", "Ocean/ Cite view", "Daily housekeeping", "Dedicated car park space", "Equipped kitchen", "Washing Machine", "Tastefully furnished"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 22,
    rating: 5.0,
    aiMatchPercent: 99,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "oniru-serviced-1br",
    title: "Oniru Serviced Apartment",
    description: "A fully furnished 1 bedroom serviced apartment",
    category: "Serviced Apartment",
    location: "Victoria Island",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    squareFootage: 1100,
    nightlyRate: 180000,
    weekendPremium: 10,
    cleaningFee: 10000,
    securityDeposit: 40000,
    image: "assets/images/horizontal/IMG-20260621-WA0124.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0124.jpg"],
    amenities: ["24/7 Power supply", "24/7 Treated water supply", "24/7 High profile security", "Highspeed broadband internet", "Netflix", "Smart TV's", "DSIV", "Housekeeping"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 15,
    rating: 4.6,
    aiMatchPercent: 92,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "cozy-2br-admiralty",
    title: "Cozy Admiralty 2BR",
    description: "Cozy 2bedroom apartment Available Today admiralty lekki phase1",
    category: "Serviced Apartment",
    location: "Lekki Phase 1",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    squareFootage: 1600,
    nightlyRate: 190000,
    weekendPremium: 15,
    cleaningFee: 15000,
    securityDeposit: 70000,
    image: "assets/images/horizontal/IMG-20260621-WA0125.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0125.jpg"],
    amenities: ["24/7 Electricity", "Smart TVs", "24/7 security", "Estate pool and gym", "Board games", "Fully equipped and fitted kitchen", "Dedicated fiber internet", "Washing machine", "Cooking spices", "Smart lock", "Fully Air-conditioned home", "Clean running water", "Elevators", "Yoga mat", "Work table and chair", "Pool toys"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 28,
    rating: 4.8,
    aiMatchPercent: 94,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "luxury-2br-admiralty",
    title: "Admiralty Luxury 2BR",
    description: "Luxury 2bedroom apartment admiralty lekki 1 available",
    category: "Luxury Villa",
    location: "Lekki Phase 1",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    squareFootage: 1900,
    nightlyRate: 240000,
    weekendPremium: 15,
    cleaningFee: 20000,
    securityDeposit: 100000,
    image: "assets/images/horizontal/IMG-20260621-WA0126.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0126.jpg"],
    amenities: ["Gated and Secured Estate", "Superfast WiFi", "24/7 Power Supply", "24/7 Security", "Swimming pool", "Smart TVs", "En-suite rooms", "Housekeeping", "Chef on demand", "Dedicated car park", "Fully equipped kitchen", "Washing machine", "Balcony sit out", "Tastefully furnished"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 19,
    rating: 4.9,
    aiMatchPercent: 96,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "celebration-package-gold",
    title: "The Golden Celebration Package",
    description: "An all-inclusive luxury weekend experience. Includes a 2-night stay in any Luxury Villa, a private chef for 2 dinners, a luxury chauffeur service for the entire duration, and a curated bouquet of local delicacies upon arrival.",
    category: "Premium Package",
    location: "Lekki Phase 1",
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 4,
    squareFootage: 2500,
    nightlyRate: 850000,
    weekendPremium: 0,
    cleaningFee: 50000,
    securityDeposit: 200000,
    image: "assets/images/horizontal/Premium bondle.jpg",
    images: ["assets/images/horizontal/Premium bondle.jpg"],
    amenities: ["Private Chef", "Chauffeur", "Gourmet Dining", "Luxury Transfers"],
    packageDetails: ["2 Nights Stay", "Private Chef (2 Dinners)", "Full Chauffeur Service", "Welcome Gift Basket"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 5,
    rating: 5.0,
    aiMatchPercent: 100,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "executive-retreat-package",
    title: "The Executive Retreat",
    description: "Designed for the high-flying professional. Includes a 3-night stay in an Executive Studio, daily breakfast service, high-speed dedicated fiber connection, and daily professional housekeeping and laundry services.",
    category: "Premium Package",
    location: "Victoria Island",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    squareFootage: 1200,
    nightlyRate: 400000,
    weekendPremium: 5,
    cleaningFee: 15000,
    securityDeposit: 50000,
    image: "assets/images/horizontal/Package.jpg",
    images: ["assets/images/horizontal/Package.jpg"],
    amenities: ["Daily Breakfast", "High-Speed Wi-Fi", "Laundry Service", "Executive Lounge Access"],
    packageDetails: ["3 Nights Stay", "Daily Breakfast", "Unlimited Fiber Internet", "Daily Laundry Service"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 3,
    rating: 4.9,
    aiMatchPercent: 95,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "ikoyi-royal-suite",
    title: "The Ikoyi Royal Suite",
    description: "Experience true royalty in this meticulously designed suite. Located in the most exclusive enclave of Ikoyi, this suite offers unparalleled privacy and elegance. Featuring hand-carved mahogany furniture, silk wall coverings, and a private terrace overlooking the lagoon.",
    category: "Penthouse",
    location: "Ikoyi",
    bedrooms: 3,
    bathrooms: 3.5,
    maxGuests: 6,
    squareFootage: 4200,
    nightlyRate: 550000,
    weekendPremium: 20,
    cleaningFee: 40000,
    securityDeposit: 300000,
    image: "assets/images/horizontal/IMG-20260621-WA0002.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0002.jpg"],
    amenities: ["Private Terrace", "Hand-carved Furniture", "Silk Wall Coverings", "24/7 Concierge", "Private Pool"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 15,
    rating: 5.0,
    aiMatchPercent: 99,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "lekki-beach-cabin",
    title: "Lekki Beachside Cabin",
    description: "A charming and intimate beachside retreat. Perfect for couples seeking a romantic getaway or a quiet escape. Directly on the sands of Lekki, offering breathtaking ocean views and the soothing sound of the waves.",
    category: "Luxury Villa",
    location: "Lekki Phase 1",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    squareFootage: 850,
    nightlyRate: 150000,
    weekendPremium: 10,
    cleaningFee: 10000,
    securityDeposit: 40000,
    image: "assets/images/horizontal/IMG-20260621-WA0004.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0004.jpg"],
    amenities: ["Beach Access", "Ocean View", "Romantic Setting", "High-Speed Wi-Fi"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 25,
    rating: 4.6,
    aiMatchPercent: 92,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "vti-executive-apartment",
    title: "VTI Executive Apartment",
    description: "A premium serviced apartment in Victoria Island, catering to business travelers. High-speed internet, ergonomic workspace, and proximity to major corporate hubs make it an ideal choice.",
    category: "Serviced Apartment",
    location: "Victoria Island",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    squareFootage: 1500,
    nightlyRate: 280000,
    weekendPremium: 5,
    cleaningFee: 20000,
    securityDeposit: 100000,
    image: "assets/images/horizontal/IMG-20260621-WA0122.jpg",
    images: ["assets/images/horizontal/IMG-20260621-WA0122.jpg"],
    amenities: ["Ergonomic Workspace", "High-Speed Internet", "Daily Housekeeping", "Gym Access"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 10,
    rating: 4.7,
    aiMatchPercent: 94,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  }
];

export const INITIAL_BOOKINGS: Booking[] = [];
export const INITIAL_TRANSACTIONS: Transaction[] = [];
export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [];
