import { Listing, Booking, Transaction, ChatMessage } from "./types";

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: "bourdillon-penthouse",
    title: "The Bourdillon Penthouse",
    description: "A breathtaking, futuristic duplex penthouse in the absolute heart of Ikoyi, Lagos. Features extensive double-height glass facades that offer pure 180-degree panoramic sweeps of the Victoria Island skyline and the glittering lagoon below at sunset. Outfitted with tailor-made leather sofas, a private wellness gym setup, custom brass and marble fixtures, and full motorized curtain integration for absolute light-level control.",
    category: "Penthouse",
    location: "Ikoyi",
    bedrooms: 4,
    bathrooms: 4.5,
    maxGuests: 8,
    nightlyRate: 450000,
    weekendPremium: 15,
    cleaningFee: 25000,
    securityDeposit: 150000,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1600566752355-f9baa0245eb7?auto=format&fit=crop&q=80&w=1000"
    ],
    amenities: ["24/7 Power", "Infinity Pool", "Private Chef", "Concierge", "High-Speed Wi-Fi", "Private Gym"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 32,
    rating: 4.9,
    aiMatchPercent: 98,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "lagoon-view-villa",
    title: "Lagoon View Villa",
    description: "Set directly on the private shoreline of Banana Island, this striking architectural achievement merges concrete facades with a tropical courtyard. Complete with an infinity lap pool that spills into the serene lagoon waters, a carded wool textile audio-shield acoustic system in the lounge room, a separate wine cellar, gourmet outdoor al fresco dining pavilion, and direct private deep-water dock access supporting yacht drop-offs.",
    category: "Luxury Villa",
    location: "Banana Island",
    bedrooms: 5,
    bathrooms: 6.0,
    maxGuests: 10,
    nightlyRate: 650000,
    weekendPremium: 15,
    cleaningFee: 35000,
    securityDeposit: 250000,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1600566752355-f9baa0245eb7?auto=format&fit=crop&q=80&w=1000"
    ],
    amenities: ["24/7 Power", "Infinity Pool", "Private Chef", "Concierge", "High-Speed Wi-Fi", "Yacht Access", "Wine Cellar"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 18,
    rating: 4.8,
    aiMatchPercent: 94,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "eko-loft",
    title: "The Eko Loft Sanctuary",
    description: "An exceptional, industrially inspired loft featuring towering double-height concrete ceilings and immense black frame ironmongery windows. Placed securely within upscale Victoria Island. Styled in close co-creation with local master carvers and modern African abstract painters. Offers a highly peaceful, safety-engineered sound insulation setup making the buzz of the metropolis vanish entirely.",
    category: "Executive Studio",
    location: "Victoria Island",
    bedrooms: 2,
    bathrooms: 2.0,
    maxGuests: 4,
    nightlyRate: 250000,
    weekendPremium: 10,
    cleaningFee: 15000,
    securityDeposit: 80000,
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=1000"
    ],
    amenities: ["24/7 Power", "High-Speed Wi-Fi", "Concierge", "Safety-pact Lock system", "Acoustic Shielding"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 45,
    rating: 4.7,
    aiMatchPercent: 91,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "ekpo-apartment",
    title: "Ekpo - Luxury 1-Bedroom",
    description: "Our Unique Studio Bedroom Apartment with Swimming Pool, Smartlock Door, complimentary breakfast, and Gym 😍✨",
    category: "Serviced Apartment",
    location: "Lekki Phase 1",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    nightlyRate: 180000,
    weekendPremium: 15,
    cleaningFee: 15000,
    securityDeposit: 50000,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=1000",
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=1000"],
    amenities: ["24/7 Power Supply", "Treated Water Supply", "High-Profile Security", "Unlimited Internet", "DSTV & Netflix", "Housekeeping Service", "Swimming Pool", "Fully Equipped Gym"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 12,
    rating: 4.8,
    aiMatchPercent: 95,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "whitestone-2br",
    title: "Whitestone - Luxury 2BR",
    description: "Luxury 2bedroom Apartment with swimming pool",
    category: "Luxury Villa",
    location: "Lekki Phase 1",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    nightlyRate: 270000,
    weekendPremium: 15,
    cleaningFee: 20000,
    securityDeposit: 100000,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1000",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1000"],
    amenities: ["Swimming Pool", "Luxury Living"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 8,
    rating: 4.7,
    aiMatchPercent: 90,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "maisonette-lekki",
    title: "Lekki Maisonette",
    description: "Newly opened 2bedroom Maisonette apartment Located at off freedom way babalola garden street",
    category: "Serviced Apartment",
    location: "Lekki Phase 1",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    nightlyRate: 210000,
    weekendPremium: 10,
    cleaningFee: 25000,
    securityDeposit: 120000,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=1000",
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=1000"],
    amenities: ["Gated and Secured Estate", "24-hour Electricity", "24-hour Safety & Security", "Guest Parking Space", "Smart TV & Netflix", "Superfast Internet", "standard gym house", "Standard Swimming Pool", "standard outdoor table tennis", "Chef on request", "Spacious Living Areas & Private Balcony", "High-Quality Bedding and Linens", "Washing Machine", "Bespoke Interior Decoration", "Netflix", "Prime video", "Elevator", "Ps5", "Cleaning services"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 5,
    rating: 4.9,
    aiMatchPercent: 97,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "victoria-penthouse",
    title: "Victoria Penthouse",
    description: "Luxury 3 bedroom penthouse with cinema",
    category: "Penthouse",
    location: "Victoria Island",
    bedrooms: 3,
    bathrooms: 3.5,
    maxGuests: 6,
    nightlyRate: 380000,
    weekendPremium: 20,
    cleaningFee: 30000,
    securityDeposit: 200000,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000"],
    amenities: ["Gated and Secured Estate", "24/7 Power Supply", "Serene environment", "Smart Lock", "Very fast internet", "Netflix / YouTube / Dstv", "Snooker Board", "Swimming pool", "Gym", "En-suite room with Balcony", "Cinema", "Ocean/ Cite view", "Daily housekeeping", "Dedicated car park space", "Equipped kitchen", "Washing Machine", "Tastefully furnished"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 22,
    rating: 5.0,
    aiMatchPercent: 99,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "oniru-serviced-1br",
    title: "Oniru Serviced Apartment",
    description: "A fully furnished 1 bedroom serviced apartment",
    category: "Serviced Apartment",
    location: "Victoria Island",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    nightlyRate: 180000,
    weekendPremium: 10,
    cleaningFee: 10000,
    securityDeposit: 40000,
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=1000",
    images: ["https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=1000"],
    amenities: ["24/7 Power supply", "24/7 Treated water supply", "24/7 High profile security", "Highspeed broadband internet", "Netflix", "Smart TV's", "DSIV", "Housekeeping"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 15,
    rating: 4.6,
    aiMatchPercent: 92,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "cozy-2br-admiralty",
    title: "Cozy Admiralty 2BR",
    description: "Cozy 2bedroom apartment Available Today admiralty lekki phase1",
    category: "Serviced Apartment",
    location: "Lekki Phase 1",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    nightlyRate: 190000,
    weekendPremium: 15,
    cleaningFee: 15000,
    securityDeposit: 70000,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=1000",
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=1000"],
    amenities: ["24/7 Electricity", "Smart TVs", "24/7 security", "Estate pool and gym", "Board games", "Fully equipped and fitted kitchen", "Dedicated fiber internet", "Washing machine", "Cooking spices", "Smart lock", "Fully Air-conditioned home", "Clean running water", "Elevators", "Yoga mat", "Work table and chair", "Pool toys"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 28,
    rating: 4.8,
    aiMatchPercent: 94,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "luxury-2br-admiralty",
    title: "Admiralty Luxury 2BR",
    description: "Luxury 2bedroom apartment admiralty lekki 1 available",
    category: "Luxury Villa",
    location: "Lekki Phase 1",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    nightlyRate: 240000,
    weekendPremium: 15,
    cleaningFee: 20000,
    securityDeposit: 100000,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1000",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1000"],
    amenities: ["Gated and Secured Estate", "Superfast WiFi", "24/7 Power Supply", "24/7 Security", "Swimming pool", "Smart TVs", "En-suite rooms", "Housekeeping", "Chef on demand", "Dedicated car park", "Fully equipped kitchen", "Washing machine", "Balcony sit out", "Tastefully furnished"],
    ownerId: "emeka-anene",
    isActive: true,
    reviewsCount: 19,
    rating: 4.9,
    aiMatchPercent: 96,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: "booking-01",
    listingId: "bourdillon-penthouse",
    listingTitle: "The Bourdillon Penthouse",
    guestName: "Alexander Sterling",
    guestEmail: "alex@sterlingholdings.com",
    guestAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDx15JuvuMcDijKEA4B_8Byjpib6fMI0fFxbYNjGPlhYAmDWvMdQMnX_byTMGQod-bhOYO4sugMfBPzJcWxb18Bmql8ORNoXufqWmoeBxtHTbACjeGG_PLhXiHkFL2osEeAHCx3O-SMpXLi_x1k6m7U63tChmAPXFuSi8NBKZZRkEVk2H9wgx0RHOtyObOSAqG24z8-V2mImw29UWFWmSYElo66Yb3acIv983sY8rqYphNg18jA9VNHTqWG9_nxNvLH1FbtnxRmPijH",
    checkIn: "2026-06-25",
    checkOut: "2026-07-02",
    guestsCount: 4,
    status: "Confirmed",
    totalAmount: 3150000,
    chefAdded: true,
    photographerAdded: false,
    jetskiAdded: true,
    services: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "booking-02",
    listingId: "lagoon-view-villa",
    listingTitle: "Lagoon View Villa",
    guestName: "Sarah Jenkins",
    guestEmail: "sjenkins@media-arts.co",
    guestAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuC9lTotMd2RIFjd-3xeK4mO_pmn_YYNyDArzN4tfbFqP4RQklnVe0rYjO7FozZUN0q1OWa3DeOu-ssQ3pyzcns_p3HivAPKLD29383WGDgK7lr1wXrwFiOhXyQL0XWXIpa6C-M3iqJWUVSZG7u5maEXPdRpMTZz4hyhjRB2ciQ2NIYsmPTdywDAsBFkZ7-a_KkFgu73NjCA6ligR5O66nIl54t-AJSB4ttjEwiRBH9ARqWh0YB7Af1tO_9g0HQ3eJmKCryEixQ-8-PF",
    checkIn: "2026-07-10",
    checkOut: "2026-07-16",
    guestsCount: 6,
    status: "Pending",
    totalAmount: 3900000,
    chefAdded: true,
    photographerAdded: true,
    jetskiAdded: false,
    services: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "booking-03",
    listingId: "eko-loft",
    listingTitle: "The Eko Loft Sanctuary",
    guestName: "Chuka Obi",
    guestEmail: "chuka@obi-studios.ng",
    guestAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuB9Lh8rkEuZ0WtuwD5WIDKt8X-Rcw_hkbPJc4me77k4fCkgvj7bw8uS_oG_i5TwGhETMSGEO8280C-iff0nUzjqzM2S4kHFg5mbfWBJzan8ih4yEEtAdcVG3RBSr9E2D2cIGqu5JReEW10IA7NXk63IzHsmjKVrqjjVOlp8L8uCHSQF6kvoikGM4EOodrcn2VvxVlXT3MdMLy4uqFdnqsmxEB_PvwDpzjr1euEh0V68xjDrRvmA70yqiRTMfrAJUIC9aGARCX0VHZCK",
    checkIn: "2026-06-22",
    checkOut: "2026-06-25",
    guestsCount: 2,
    status: "Confirmed",
    totalAmount: 750000,
    chefAdded: false,
    photographerAdded: false,
    jetskiAdded: false,
    services: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-01",
    date: "2026-06-21",
    reference: "CL-TX8924",
    type: "Booking Revenue",
    amount: 1200000,
    status: "Processed",
    description: "Lagoon View Villa booking - Sarah Jenkins",
    userId: "emeka-anene",
    createdAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "tx-02",
    date: "2026-06-20",
    reference: "CL-TX8921",
    type: "Payout",
    amount: -2500000,
    status: "Processed",
    description: "GTBank withdrawal to account ending in **3492",
    userId: "emeka-anene",
    createdAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "tx-03",
    date: "2026-06-18",
    reference: "CL-TX8901",
    type: "Booking Revenue",
    amount: 3150000,
    status: "Processed",
    description: "The Bourdillon Penthouse booking - Alexander Sterling",
    userId: "emeka-anene",
    createdAt: "2024-01-01T00:00:00Z"
  },
  {
    id: "tx-04",
    date: "2026-06-15",
    reference: "CL-TX8875",
    type: "Booking Revenue",
    amount: 450000,
    status: "Processed",
    description: "The Eko Loft booking - Amina Alabi",
    userId: "emeka-anene",
    createdAt: "2024-01-01T00:00:00Z"
  }
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "msg-01",
    sender: "concierge",
    text: "Good morning, Alexander. I have verified your upcoming stay at The Bourdillon Penthouse in Ikoyi. Would you like me to pre-book key airport transfers or assign a private chef for your arrival evening?",
    timestamp: "8:30 AM"
  }
];

export const CONCIERGE_FAQ_TRIGGERS = [
  {
    keywords: ["chef", "dinner", "food", "cook", "dining"],
    response: "Certainly! Cozy Lagos boasts five-star in-house chefs specialized in local West African gourmet fusion and custom continental diets. I can schedule a chef session for your stay duration (₦30,000 per day plus cost of ingredients) or for an exclusive single-night dinner. Which would you prefer?"
  },
  {
    keywords: ["driver", "car", "transfer", "chauffeur", "airport", "transport"],
    response: "Absolutely. I can secure a bulletproof executive SUV or private luxury sedan with an vetted professional security chauffeur for your time in Lagos. Airport pickup transfers are typically ₦120,000, or you can retain full daily service starting at ₦250,000 / day. Shall I lock this down for your dates?"
  },
  {
    keywords: ["yacht", "boat", "cruise", "island", "party"],
    response: "Our 65ft private luxury yacht experience is the premier lagoon journey in West Africa! It offers custom 6-hour charters setting sail from Victoria Island, complete with a private chef, champagne reception, and custom sunset cruising options. It is highly limited, so let me know if you would like me to put a pending request for your stay!"
  },
  {
    keywords: ["checkout", "late", "extend", "time"],
    response: "Understood, Alexander. Standard checkout is 11:00 AM, but I can coordinate with Sarah, your host, to secure an elegant late checkout up to 3:00 PM for you (pending incoming guest clean cycles). Let me ask her right away to obtain key clearance."
  },
  {
    keywords: ["power", "electricity", "safety", "secure"],
    response: "Safety and continuity are guaranteed. Every elite portal under Cozy Lagos maintains dual heavy industrial generators plus heavy battery inverter/solar grid backups ensuring full 24/7 power, robust water treatment plants, and armed external neighborhood perimeter patrols."
  }
];
